In [21]:
import pandas as pd
import numpy as np
base_url = 'https://trisonics-scouting-api.azurewebsites.net/api'


def get_scouted_data_url(secret_key, event_key):
    return f'{base_url}/GetResults?secret_team_key={secret_key}&event_key={event_key}'  # noqa


def get_opr_data_url(secret_key, event_key):
    return f"{base_url}/GetOPRData?secret_team_key={secret_key}&event_key={event_key}"  # noqa


url = get_scouted_data_url('4003data', '2023micmp4')
opr_url = get_opr_data_url('4003data', '2023micmp4')
scouted_data = pd.read_json(url)
opr_data = pd.read_json(opr_url)

In [22]:
opr_data.head()

adjustPoints  autoChargeStationPoints  autoGamePieceCount  \
0             0                 4.567160            1.720137   
1             0                 3.019844            1.610851   
2             0                 4.041899            2.279780   
3             0                 2.781981            1.369659   
4             0                 3.384052            1.529111   

   autoGamePiecePoints  autoMobilityPoints  autoPoints  coopGamePieceCount  \
0             8.773685            1.948338   15.289183            2.442987   
1             9.916528            2.506831   15.443203            2.586447   
2            12.693704            2.737445   19.473048            2.729082   
3             8.030216            3.176905   13.989103            2.608533   
4             7.202284            2.163092   12.749427            2.100227   

   endGameChargeStationPoints  endGameParkPoints  foulCount  foulPoints  \
0                    9.477199           0.067777  -0.216091    7.554056   
1                    7.313829           0.414749   0.518224   -0.910814   
2                   10.348966          -0.144478   0.075065    0.768282   
3                    9.306831           0.778561  -0.034882    0.775411   
4                    6.235532           0.743576   0.391607    4.312660   

   linkPoints        rp  techFoulCount  teleopGamePieceCount  \
0   12.506784  1.402379      -0.048580              7.864378   
1   14.645081  1.878368       0.052596              8.760601   
2   13.466441  1.989179      -0.015095              8.096853   
3   10.764902  1.018568       0.170315              8.194082   
4   11.177161  1.526265       0.164783              8.322655   

   teleopGamePiecePoints  teleopPoints  totalChargeStationPoints  totalPoints  \
0              23.014597     32.559572                 14.044359    67.909595   
1              23.555304     31.283882                 10.333673    60.461353   
2              16.435192     26.639680                 14.390865    60.347452   
3              23.354368     33.439760                 12.088811    58.969175   
4              23.243392     30.222500                  9.619583    58.461747   

   teamNumber  
0        5712  
1          51  
2        3175  
3        3655  
4        1701

In [23]:
opr_data[ opr_data.teamNumber == 51 ].totalPoints.item()

60.4613527653

In [24]:
vardata = scouted_data.drop(['event_key', 'match_key', 'match_notes',
                            'scouter_name', 'secret_team_key'], axis=1)

summed = vardata.groupby('scouting_team').sum().reset_index()
summed.head()

scouting_team  auto_nothing  auto_engaged  auto_docked  auto_community  \
0              0             0             0            0               0   
1             51             0             0            0               9   
2             70             0             2            0               9   
3             74             0             0            0               9   
4            107             2             3            1               5   

   endgame_nothing  endgame_dead_robot  endgame_engaged  endgame_docked  \
0                0                   0                0               0   
1                0                   0                7               1   
2                0                   0                7               3   
3                0                   0               10               0   
4                0                   2                5               3   

   endgame_parked  ...  auto_cubes_low  auto_cones_high  auto_cones_medium  \
0               0  ...               0                0                  0   
1               1  ...               0                8                  0   
2               0  ...               1                7                  0   
3               0  ...               0                0                  0   
4               0  ...               0                0                  0   

   auto_cones_low  teleop_cubes_high  teleop_cubes_medium  teleop_cubes_low  \
0               0                  0                    0                 0   
1               1                  9                    5                 5   
2               0                  3                    9                 5   
3               0                  4                    0                13   
4               1                  3                    2                 5   

   teleop_cones_high  teleop_cones_medium  teleop_cones_low  
0                  0                    0                 0  
1                 20                    8                 5  
2                 18                    9                 6  
3                 20                    1                 5  
4                 13                    5                 6  

[5 rows x 22 columns]

In [25]:
demeaned = summed.copy()
numerical_cols = list(set(demeaned.columns) - set(['scouting_team']))
demeaned.loc[:, numerical_cols] = demeaned.loc[:, numerical_cols] - demeaned.loc[:, numerical_cols].mean()
demeaned.head()

scouting_team  auto_nothing  auto_engaged  auto_docked  auto_community  \
0              0     -0.439024     -2.292683    -0.317073       -7.219512   
1             51     -0.439024     -2.292683    -0.317073        1.780488   
2             70     -0.439024     -0.292683    -0.317073        1.780488   
3             74     -0.439024     -2.292683    -0.317073        1.780488   
4            107      1.560976      0.707317     0.682927       -2.219512   

   endgame_nothing  endgame_dead_robot  endgame_engaged  endgame_docked  \
0        -0.195122           -0.243902        -6.390244       -0.707317   
1        -0.195122           -0.243902         0.609756        0.292683   
2        -0.195122           -0.243902         0.609756        2.292683   
3        -0.195122           -0.243902         3.609756       -0.707317   
4        -0.195122            1.756098        -1.390244        2.292683   

   endgame_parked  ...  auto_cubes_low  auto_cones_high  auto_cones_medium  \
0       -1.219512  ...       -1.512195        -3.097561          -0.585366   
1       -0.219512  ...       -1.512195         4.902439          -0.585366   
2       -1.219512  ...       -0.512195         3.902439          -0.585366   
3       -1.219512  ...       -1.512195        -3.097561          -0.585366   
4       -1.219512  ...       -1.512195        -3.097561          -0.585366   

   auto_cones_low  teleop_cubes_high  teleop_cubes_medium  teleop_cubes_low  \
0       -0.853659          -4.219512            -3.487805         -7.121951   
1        0.146341           4.780488             1.512195         -2.121951   
2       -0.853659          -1.219512             5.512195         -2.121951   
3       -0.853659          -0.219512            -3.487805          5.878049   
4        0.146341          -1.219512            -1.487805         -2.121951   

   teleop_cones_high  teleop_cones_medium  teleop_cones_low  
0         -11.902439            -6.268293         -3.317073  
1           8.097561             1.731707          1.682927  
2           6.097561             2.731707          2.682927  
3           8.097561            -5.268293          1.682927  
4           1.097561            -1.268293          2.682927  

[5 rows x 22 columns]

In [26]:
A = demeaned.loc[:, numerical_cols].to_numpy().T
N = A.shape[1]
C = 1/N*(A@A.T)
r = np.linalg.eig(C)

variances = {}
for col, v in zip(numerical_cols, np.diag(C)):
    variances[col] = v

variances

{'auto_docked': 0.5092207019631178,
 'auto_cones_low': 3.0517549077929798,
 'endgame_dead_robot': 0.23319452706722194,
 'auto_cubes_high': 12.134443783462226,
 'teleop_cones_low': 13.045806067816777,
 'auto_engaged': 6.402141582391433,
 'endgame_engaged': 5.213563355145743,
 'endgame_parked': 2.0737656157049367,
 'endgame_nothing': 0.15704937537180252,
 'endgame_docked': 0.8411659726353365,
 'teleop_cones_medium': 31.464604402141582,
 'auto_nothing': 0.44140392623438446,
 'teleop_cubes_low': 69.81439619274245,
 'teleop_cubes_medium': 6.932778108268886,
 'auto_cubes_medium': 1.7989292088042848,
 'auto_community': 4.659131469363476,
 'auto_cones_high': 13.063652587745391,
 'teleop_cubes_high': 10.561570493753724,
 'auto_cones_medium': 3.754907792980371,
 'teleop_cones_high': 63.30755502676979,
 'auto_cubes_low': 5.079119571683523}

In [27]:
from sklearn.cluster import KMeans
score_vectors = (
    scouted_data.groupby('scouting_team')
                .sum(numeric_only=True)
                .reset_index()
)
avail_cols = ['teleop_cubes_high']
data_cols = avail_cols
v = score_vectors.loc[:, data_cols]
model = KMeans(4,
                random_state=1,
                init='random',
                n_init=10,
                max_iter=100)
v = score_vectors.loc[:, data_cols]
model.fit(v.to_numpy())

KMeans(init='random', max_iter=100, n_clusters=4, n_init=10, random_state=1)

In [28]:
from scout import *

In [29]:
url = get_team_list_url('2023micmp4')
df = pd.read_json(url)

In [30]:
df.head()

number                   name  \
0      51          Wings of Fire   
1      70          More Martians   
2      74             Team CHAOS   
3     107  Team R.O.B.O.T.I.C.S.   
4     226            Hammerheads   

                                             locaton  
0  International Technology Acad & Pontiac High S...  
1                               Goodrich High School  
2    Holland High School & Black River Public School  
3                      Holland Christian High School  
4                                   Troy High School

In [60]:
import numpy as np

from scout import get_secret_key, get_event_key, load_event_data

scouted_data = load_event_data('4003data', '2023micmp4')
score_vectors = (
    scouted_data
    .groupby("scouting_team")
    .mean(numeric_only=True)
    .reset_index()
)

A = score_vectors.drop('scouting_team', axis=1)
A.sub(A.mean())
N = A.shape[1]
C = 1/N*(A@A.T)
eigenvalues, P = np.linalg.eigh(C)
eigens = [np.real(x) for x in eigenvalues]
eigens.reverse()
(eigens[0] + eigens[1]) / sum(eigens)

https://trisonics-scouting-api.azurewebsites.net/api/GetResults?secret_team_key=4003data&event_key=2023micmp4


0.9918322933434331

In [57]:
D.shape, P.shape, P

((41,),
 (41, 41),
 array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-1.67884648e-07,  0.00000000e+00,  0.00000000e+00, ...,
          1.06248279e-01, -1.84310285e-01,  2.39819443e-01],
        [ 4.74575621e-01, -1.23260307e-02,  1.14643209e-01, ...,
          8.70347774e-02, -1.87124571e-01,  1.93480591e-01],
        ...,
        [ 4.90378950e-02, -1.51416584e-01, -2.93272596e-02, ...,
         -2.80420539e-01, -3.29375043e-02,  5.39100139e-02],
        [-2.27943239e-03,  2.70604452e-01, -5.86705065e-03, ...,
         -1.96789580e-02, -2.48392192e-01,  2.06354531e-02],
        [ 1.40098087e-01, -1.58277641e-01, -6.79705516e-02, ...,
          2.70594920e-02,  4.26439739e-02,  1.22508426e-01]]))

In [53]:
P.shape[0]

41

In [58]:
for c in range(P.shape[0]):
    print(
        np.linalg.norm(P[:, c])
    )

0.9999999999999989
0.9999999999999998
0.9999999999999994
0.9999999999999998
0.9999999999999992
0.9999999999999991
0.9999999999999998
1.0
1.0
1.0
1.0000000000000004
0.9999999999999997
0.9999999999999997
1.0
0.9999999999999991
0.9999999999999999
0.9999999999999994
1.0000000000000002
0.9999999999999986
1.000000000000001
1.0
0.9999999999999999
0.9999999999999998
1.0000000000000002
1.0
1.0
0.9999999999999998
1.0000000000000004
0.9999999999999996
0.9999999999999996
0.9999999999999993
1.0000000000000002
1.0000000000000002
0.9999999999999988
1.0
0.9999999999999999
1.0000000000000007
1.0000000000000002
0.999999999999999
0.9999999999999988
0.9999999999999996


In [34]:
eigens = eigens.reverse()
norm = np.linalg.norm
Q = np.array([
    r.eigenvectors[0],
    r.eigenvectors[1],
]).T

proj = Q.T @ A
sum(eigens)
for e in eigens:
    print(e)

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/home/jbuist/git/FRCScout/data-streamlit/venv/lib/python3.11/site-packages/pandas/core/frame.py", line 1693, in __rmatmul__
    return self.T.dot(np.transpose(other)).T
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbuist/git/FRCScout/data-streamlit/venv/lib/python3.11/site-packages/pandas/core/frame.py", line 1647, in dot
    raise ValueError(
ValueError: Dot product shape mismatch, (23, 41) vs (21, 2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jbuist/git/FRCScout/data-streamlit/venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_73433/144619270.py", line 8, in <module>
    proj = Q.T @ A
           ~~~~^~~
  File "/home/jbuist/git/FRCScout/data-streamlit/venv/lib/python3.11/site-packages/pandas/core/generic.py", line 2102, in __array_ufunc_

In [35]:
v1 = r.eigenvectors[0]
v2 = r.eigenvectors[1]

v1, norm(v1), v2, norm(v2)

(array([ 1.76912585e-03, -2.52268087e-04, -2.43590166e-03,  6.39147799e-02,
        -2.95742169e-02, -4.19388716e-02, -2.29674813e-02,  2.53767410e-02,
         2.03762426e-03, -1.19177201e-01,  1.67547818e-02,  1.97252906e-01,
        -7.89562085e-02, -1.04417885e-01, -1.72215953e-01, -3.81081028e-02,
        -5.59330169e-01,  5.63075102e-01,  4.85569049e-01, -1.57350797e-01,
        -3.98441347e-03]),
 0.9999999999999986,
 array([ 0.01354461, -0.04510684,  0.06964848,  0.10666706,  0.20181625,
        -0.08120083, -0.14076171, -0.14984617, -0.18873037, -0.09465259,
         0.65389609, -0.0871979 ,  0.07833769,  0.52784272,  0.27361338,
        -0.11971762,  0.03293509,  0.142711  ,  0.03412006, -0.10739972,
        -0.06402234]),
 1.0000000000000004)